### ISSUE TITLE
"Start Ranking" doesn't work

### ISSUE THREAD

**Issue by zeke** [zooniverse/sunspotter#18]
I'm on macOS 10.11.4 Chrome. When I click the [Start Ranking] button, nothing happens.

![screen shot 2016-06-23 at 10 11 43 pm](https://cloud.githubusercontent.com/assets/2289/16328486/93b36034-398f-11e6-94a0-ebaed3dc355e.png)

**Comment by parrish** [comment]
We actually just finished the data!  The site reflects that now in e2c36fa

**Comment by zeke** [comment]
👏
